<div class="hm_banner_wrapper">
            <div id="rev_slider_1068_1_wrapper" class="rev_slider_wrapper fullscreen-container" data-alias="levano4export" data-source="gallery" style="background-color:transparent;padding:0px;">
                <div id="rev_slider_1068_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.3.0.2">
                    <ul>
                        <li data-index="rs-3010" data-transition="boxfade" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="1000" data-thumb="" data-rotate="0" data-fstransition="boxfade" data-fsmasterspeed="1000" data-fsslotamount="7" data-saveperformance="off" data-title="Intro" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                            <!-- MAIN IMAGE -->
                            <div class="tp-caption tp-shape tp-shapewrapper " id="slide-2800-layer-7" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames='[{"from":"opacity:0;","speed":500,"to":"o:1;","delay":0,"ease":"Power4.easeOut"},{"speed":5000,"to":"opacity:0;","ease":"Power4.easeInOut"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;background-color:rgba(0, 0, 0, 0.60);border-color:rgba(0, 0, 0, 0);border-width:0px;"> </div>
                            <img src="assets/banner/sumit.jpg" alt="handmade-craft-slide1" data-lazyload="assets/banner/sumit.jpg" data-bgposition="center center" data-kenburns="on" data-duration="20000" data-ease="Power1.easeOut" data-scalestart="110" data-scaleend="100" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="0 0" class="rev-slidebg" data-no-retina>

                            <!-- LAYER NR. 1 -->
                            <div class="tp-caption sfb sfb tp-resizeme" data-x="center" data-y="center" data-hoffset="0" data-voffset="-240" data-speed="1500" data-start="1000" data-easing="easeOutBounce" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-fontsize="['40','30','20','20']" data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];","speed":2000,"to":"o:1;","delay":1500,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"Power2.easeInOut"}]' data-endeasing="Power4.easeIn" style="font-size:40px;line-height:140px;text-transform:capitalize;text-shadow: -4px 4px 3px rgba(51, 51, 51, 0.35);z-index:100;">
                                
                            </div>

                            <!-- LAYER NR. 1 -->
                            <div class="tp-caption sfb sfb tp-resizeme" data-x="center" data-y="center" data-hoffset="0" data-voffset="-150" data-speed="1500" data-start="1000" data-easing="easeOutBounce" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-fontsize="['55','50','40','30']" data-frames='[{"from":"x:[105%];z:0;rX:45deg;rY:0deg;rZ:90deg;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":2000,"to":"o:1;","delay":1000,"split":"chars","splitdelay":0.05,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[100%];","mask":"x:inherit;y:inherit;","ease":"Power2.easeInOut"}]' data-endeasing="Power4.easeIn" style="font-size:55px;color:#FFFFFF;line-height:140px;text-transform:uppercase;font-weight:600;text-shadow: -4px 4px 3px rgba(51, 51, 51, 0.35);z-index:100;font-family: 'Roboto Slab', serif;letter-spacing:5px;">
                                Craft Village India
                            </div>

                            <!-- LAYER NR. 2 -->
                            <div class="tp-caption Restaurant-Cursive   tp-resizeme" id="slide-3010-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-60','-60','-70','-70']" data-width="none" data-height="none" data-whitespace="nowrap" data-fontsize="['18','18','15','15']" data-type="text" data-responsive_offset="on" data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":700,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,20]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,20]" style="z-index: 6; white-space: nowrap; line-height:26px;text-transform:left;font-family: 'Roboto', sans-serif;letter-spacing:0px;">In Craft Village, we will provide the platform to the customers to buy and sell handcraft material</div>

                        </li>
                    </ul>
                </div>
            </div>
        </div>